[tool.ruff]
# Enable Pyflakes (`F`), pycodestyle (`E`), isort (`I`), and McCabe complexity (`C90`)
target-version = "py310"

# Line length is set to 100 characters
line-length = 100

# Allow unused variables when underscore-prefixed
select = ["E", "F", "I", "N", "B", "A", "C4", "UP", "W"]

# Exclude directories and files
exclude = [
    ".bzr",
    ".git",
    ".hg",
    ".svn",
    ".tox",
    ".venv",
    "venv",
    "__pycache__",
    "_build",
    "buck-out",
    "build",
    "dist",
]

[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"

# Indent with 4 spaces
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false 